from phil.contracts.base import Contract, Part
from phil.contracts.common import Claim, Issue, SelfCheck
from phil.contracts.inputs import (
    ArchitectInput,
    BtwInput,
    CriticInput,
    ImplementInput,
    IntakeInput,
    ReviewInput,
    TesterInput,
)
from phil.contracts.interface import Brief, Decision, Goal, ParkedItem, Ref, RunStatus
from phil.contracts.planning import Plan, PlanCritique, QuickTask, Task
from phil.contracts.results import AttemptWorklog, Review, TaskResult, TesterReport, TestReport, Worklog
from phil.contracts.routing import Answer, AnswerInput, RouteInput, RouteJudgement

ALL_CONTRACTS: list[type[Contract]] = [
    Plan,
    PlanCritique,
    TaskResult,
    TestReport,
    TesterReport,
    Review,
    Goal,
    Brief,
    ParkedItem,
    RunStatus,
    ArchitectInput,
    BtwInput,
    CriticInput,
    ImplementInput,
    IntakeInput,
    TesterInput,
    ReviewInput,
    RouteInput,
    RouteJudgement,
    AnswerInput,
    Answer,
]

__all__ = [
    "ALL_CONTRACTS",
    "Answer",
    "AnswerInput",
    "ArchitectInput",
    "AttemptWorklog",
    "Brief",
    "BtwInput",
    "Claim",
    "Contract",
    "CriticInput",
    "Decision",
    "Goal",
    "ImplementInput",
    "IntakeInput",
    "Issue",
    "ParkedItem",
    "Part",
    "Plan",
    "PlanCritique",
    "QuickTask",
    "Ref",
    "Review",
    "ReviewInput",
    "RouteInput",
    "RouteJudgement",
    "RunStatus",
    "SelfCheck",
    "Task",
    "TaskResult",
    "TesterInput",
    "TesterReport",
    "TestReport",
    "Worklog",
]
