from phil.contracts.base import Contract, Part
from phil.contracts.common import Claim, Issue, SelfCheck
from phil.contracts.design import Approach, Approaches, DesignInput
from phil.contracts.inputs import (
    ArchitectInput,
    BtwInput,
    CriticInput,
    ImplementInput,
    IntakeInput,
    ReviewInput,
    TesterInput,
)
from phil.contracts.interface import Brief, Decision, Goal, ParkedItem, Question, Ref, RunStatus
from phil.contracts.planning import Plan, PlanCritique, QuickTask, Task
from phil.contracts.results import AttemptWorklog, Review, TaskResult, TesterReport, TestReport, Worklog
from phil.contracts.routing import Answer, AnswerInput, RouteInput, RouteJudgement

ALL_CONTRACTS: list[type[Contract]] = [
    Plan,
    PlanCritique,
    TaskResult,
    TestReport,
    TesterReport,
    Review,
    Goal,
    Brief,
    ParkedItem,
    RunStatus,
    ArchitectInput,
    BtwInput,
    CriticInput,
    ImplementInput,
    IntakeInput,
    TesterInput,
    ReviewInput,
    RouteInput,
    RouteJudgement,
    AnswerInput,
    Answer,
    Approaches,
    DesignInput,
]

__all__ = [
    "ALL_CONTRACTS",
    "Answer",
    "AnswerInput",
    "Approach",
    "Approaches",
    "ArchitectInput",
    "AttemptWorklog",
    "Brief",
    "BtwInput",
    "Claim",
    "Contract",
    "CriticInput",
    "Decision",
    "DesignInput",
    "Goal",
    "ImplementInput",
    "IntakeInput",
    "Issue",
    "ParkedItem",
    "Part",
    "Plan",
    "PlanCritique",
    "Question",
    "QuickTask",
    "Ref",
    "Review",
    "ReviewInput",
    "RouteInput",
    "RouteJudgement",
    "RunStatus",
    "SelfCheck",
    "Task",
    "TaskResult",
    "TesterInput",
    "TesterReport",
    "TestReport",
    "Worklog",
]
